export {default as Create} from './create'
export {default as Home} from './home'
export {default as Login} from './login'
export {default as View} from './view'
export {default as Signup} from './signup'
